[package]
name = "bridge"
version = "0.1.0"
edition = "2021"

[features]
regtest = ["dep:bitcoincore-rpc", "dep:tempfile"]

[dependencies]
bitcoin = "0.32"
bitcoin-scriptexec = { git = "https://github.com/BitVM/rust-bitcoin-scriptexec" }
bitcoincore-rpc = { version = "0.19", optional = true }
lamport = { path = "../lamport" }
rand = "0.8"
tempfile = { version = "3", optional = true }
